INSERT INTO designation (`id`,`designation_name`,`responsibilities`) VALUES (1,'Company Admin','Admin');
INSERT INTO designation (`id`,`designation_name`,`responsibilities`) VALUES (2,'HR Manager','HR');
INSERT INTO designation (`id`,`designation_name`,`responsibilities`) VALUES (3,'Project Manager','PM');
INSERT INTO designation (`id`,`designation_name`,`responsibilities`) VALUES (4,'Software Engineer','Dev');
INSERT INTO designation (`id`,`designation_name`,`responsibilities`) VALUES (5,'QA Engineer','QA');

INSERT INTO employee (`id`,`active`,`address`,`availability`,`bench`,`date_of_birth`,`designation_id`,`email`,`first_name`,`join_date`,`last_name`,`password`,`phone_number`,`username`,`sub_module_availability`) VALUES (1,'Yes','Head Office',100,'No','1992-09-09',1,'admin@sgic.com','Admin','2019-12-18','Admin','LeX1rt9qeFzuhhVnmpLZzzVIzXjE17N0BMTqbebIuk+Rw4Tga24b96giRcr0b9LV','0777123456','admin',100);
INSERT INTO employee (`id`,`active`,`address`,`availability`,`bench`,`date_of_birth`,`designation_id`,`email`,`first_name`,`join_date`,`last_name`,`password`,`phone_number`,`username`,`sub_module_availability`) VALUES (2,'Yes','Head Office',100,'No','1992-09-09',2,'admin@sgic.com','HR','2019-12-18','HR','LeX1rt9qeFzuhhVnmpLZzzVIzXjE17N0BMTqbebIuk+Rw4Tga24b96giRcr0b9LV','0777123456','hr',100);
INSERT INTO employee (`id`,`active`,`address`,`availability`,`bench`,`date_of_birth`,`designation_id`,`email`,`first_name`,`join_date`,`last_name`,`password`,`phone_number`,`username`,`sub_module_availability`) VALUES (3,'Yes','Head Office',100,'No','1992-09-09',3,'admin@sgic.com','PM','2019-12-18','PM','LeX1rt9qeFzuhhVnmpLZzzVIzXjE17N0BMTqbebIuk+Rw4Tga24b96giRcr0b9LV','0777123456','pm',100);
INSERT INTO employee (`id`,`active`,`address`,`availability`,`bench`,`date_of_birth`,`designation_id`,`email`,`first_name`,`join_date`,`last_name`,`password`,`phone_number`,`username`,`sub_module_availability`) VALUES (4,'Yes','Head Office',100,'No','1992-09-09',4,'admin@sgic.com','Dev','2019-12-18','Dev','LeX1rt9qeFzuhhVnmpLZzzVIzXjE17N0BMTqbebIuk+Rw4Tga24b96giRcr0b9LV','0777123456','dev',100);
INSERT INTO employee (`id`,`active`,`address`,`availability`,`bench`,`date_of_birth`,`designation_id`,`email`,`first_name`,`join_date`,`last_name`,`password`,`phone_number`,`username`,`sub_module_availability`) VALUES (5,'Yes','Head Office',100,'No','1992-09-09',5,'admin@sgic.com','QA','2019-12-18','QA','LeX1rt9qeFzuhhVnmpLZzzVIzXjE17N0BMTqbebIuk+Rw4Tga24b96giRcr0b9LV','0777123456','qa',100);