INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (1,b'1',b'0','Company Dashboard',b'0',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (2,b'1',b'0','Developer Dashboard',b'0',b'0',b'1');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (3,b'1',b'0','PM Dashboard',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (4,b'1',b'0','QA Dashboard',b'0',b'1',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (5,b'1',b'1','HR Dashboard',b'0',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (6,b'1',b'1','View Employee',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (7,b'1',b'1','Add Employee',b'0',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (8,b'1',b'1','Edit Employee',b'0',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (9,b'1',b'1','More View Employee',b'0',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (10,b'1',b'1','Delete Employee',b'0',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (11,b'1',b'0','View Client',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (12,b'1',b'0','Add Client',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (13,b'1',b'0','Edit Client',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (14,b'1',b'0','Delete Client',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (15,b'1',b'0','View Project',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (16,b'1',b'0','Add Project',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (17,b'1',b'0','Edit Project',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (18,b'1',b'0','Delete Project',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (19,b'1',b'0','View Module',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (20,b'1',b'0','Add Module',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (21,b'1',b'0','Edit Module',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (22,b'1',b'0','Delete Module',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (23,b'1',b'0','View Submodule',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (24,b'1',b'0','Add Submodule',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (25,b'1',b'0','Edit Submodule',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (26,b'1',b'0','Delete Submodule',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (27,b'1',b'1','View Project Allocation',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (28,b'1',b'1','Allocate Project',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (29,b'1',b'1','Deallocate Project',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (30,b'1',b'1','View Module Allocation',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (31,b'1',b'1','Allocate Module',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (32,b'1',b'1','Deallocate Module',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (33,b'1',b'0','View Defect',b'1',b'1',b'1');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (34,b'1',b'0','Add Defect',b'0',b'1',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (35,b'1',b'0','Edit Defect',b'0',b'1',b'1');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (36,b'1',b'0','Delete Defect',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (37,b'1',b'0','More View Defect',b'1',b'1',b'1');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (38,b'1',b'1','Update User Profile',b'1',b'1',b'1');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (39,b'1',b'1','View Designation',b'0',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (40,b'1',b'1','Add Designation',b'0',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (41,b'1',b'1','Edit Designation',b'0',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (42,b'1',b'1','Delete Designation',b'0',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (43,b'1',b'0','View Role',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (44,b'1',b'0','Add Role',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (45,b'1',b'0','Edit Role',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (46,b'1',b'0','Delete Role',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (47,b'1',b'0','View Priority',b'1',b'1',b'1');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (48,b'1',b'0','Add Priority',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (49,b'1',b'0','Edit Priority',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (50,b'1',b'0','Delete Priority',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (51,b'1',b'0','View Severity',b'1',b'1',b'1');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (52,b'1',b'0','Add Severity',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (53,b'1',b'0','Edit Severity',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (54,b'1',b'0','Delete Severity',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (55,b'1',b'0','View Type',b'1',b'1',b'1');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (56,b'1',b'0','Add Type',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (57,b'1',b'0','Edit Type',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (58,b'1',b'0','Delete Type',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (59,b'1',b'0','View Status',b'1',b'1',b'1');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (60,b'1',b'0','Add Status',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (61,b'1',b'0','Edit Status',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (62,b'1',b'0','Delete Status',b'1',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (63,b'1',b'0','Set Privileges',b'0',b'0',b'0');
INSERT INTO privilege (`id`,`company_admin`,`hr_manager`,`name`,`project_manager`,`qa_engineer`,`software_engineer`) VALUES (64,b'1',b'0','View Defect Log',b'1',b'1',b'1');
